config/routes.rb
Rails.application.routes.draw do
  resources :game_rooms
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'game_rooms#index'

  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback' # for use with Github, Facebook
  get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider
  delete 'logout' => 'oauths#logout', as: :logout
end

app/models/User.rb
class User < ApplicationRecord
  authenticates_with_sorcery! do |config|
    config.authentications_class = Authentication
  end
  has_many :authentications, :dependent => :destroy
  accepts_nested_attributes_for :authentications
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user
end

app/models/game.rb
class Game
  STATE = {
    GAME_INIT: 0,
    GAME_PROCESSING: 1,
    GAME_ENDING: 2,
    GAME_COMPLETED: 3
  }

  MODE = {
    "基本 5 色": 0,
    "6 色 10 張": 1,
    "6 色 5 張": 2,
    "彩色": 3,
  }

  attr_accessor :id, :name, :mode, :players, :state, :game_room_id, :game_room

  def initialize(game_room)
    @game_room = game_room
    params = game_room.game_data || {}

    @id = game_room.id
    @name = game_room.name
    @mode = params.dig "mode"
    @players = params.dig "players"
    @current_player = nil
    @deck = []
    @discards = []
    @state = STATE[:GAME_INIT]
    @fire_token = nil
    @info_token = nil
  end

  def save
    game_room.game_data ||= {}
    game_room.game_data['state'] = state
    game_room.save
  end
end

app/models/game_room.rb
class GameRoom < ApplicationRecord

  broadcasts_to ->(game_room) { "game_rooms" }, inserts_by: :prepend
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/game_rooms_controller.rb
class GameRoomsController < ApplicationController
  before_action :set_game_room, only: %i[ show edit update destroy ]

  # GET /game_rooms or /game_rooms.json
  def index
    @game_rooms = GameRoom.order(id: :desc)
  end

  # GET /game_rooms/1 or /game_rooms/1.json
  def show
  end

  # GET /game_rooms/new
  def new
    @game_room = GameRoom.new
  end

  # GET /game_rooms/1/edit
  def edit
  end

  # POST /game_rooms or /game_rooms.json
  def create
    @game_room = GameRoom.new(game_room_params) { _1.game_data = {players: [] , state: 0} }

    respond_to do |format|
      if @game_room.save
        format.html { redirect_to game_room_url(@game_room), notice: "Game room was successfully created." }
        format.json { render :show, status: :created, location: @game_room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /game_rooms/1 or /game_rooms/1.json
  def update
    respond_to do |format|
      if @game_room.update(game_room_params)
        format.html { redirect_to game_room_url(@game_room), notice: "Game room was successfully updated." }
        format.json { render :show, status: :ok, location: @game_room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /game_rooms/1 or /game_rooms/1.json
  def destroy
    @game_room.destroy

    respond_to do |format|
      format.html { redirect_to game_rooms_url, notice: "Game room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game_room
      @game_room = GameRoom.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_room_params
      params.require(:game_room).permit(:name, :game_data)
    end
end

app/controllers/oauths_controller.rb
# frozen_string_literal: true

class OauthsController < ApplicationController
  skip_before_action :require_login, raise: false

  # sends the user on a trip to the provider,
  # and after authorizing there back to the callback url.
  def oauth
    provider = params[:provider]
    if Rails.env.production?
      login_at(provider)
    else

      @user = User.find_or_create_by email: "#{provider}_user@local.host",
                                     name: "local_#{provider}_user"
      cookies.encrypted['user_id'] = @user.id
      auto_login(@user)

      redirect_to root_path, notice: "Logged in from #{provider.titleize}!"
    end
  end

  # Resets the session and runs hooks before and after.
  def logout
    return unless logged_in?

    before_logout!
    cookies.delete 'user_id'
    ActionCable.server.remote_connections.where(current_user:).disconnect
    reset_sorcery_session
    after_logout!(current_user)

    redirect_to root_path, notice: 'Logged out!', status: 303
  end

  def callback
    provider = params[:provider]
    if (@user = login_from(provider))
      cookies.encrypted['user_id'] = @user.id

      redirect_to root_path, notice: "Logged in from #{provider.titleize}!"
    else
      begin
        @user = create_from(provider)
        # NOTE: this is the place to add '@user.activate!' if you are using user_activation submodule

        reset_session # protect from session fixation attack
        cookies.encrypted['user_id'] = @user.id
        auto_login(@user)
        redirect_to root_path, notice: "Logged in from #{provider.titleize}!"
      rescue StandardError => e
        pp '&' * 100
        pp e
        pp '&' * 100
        redirect_to root_path, alert: "Failed to login from #{provider.titleize}!"
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_rooms_helper.rb
module GameRoomsHelper
end

app/views/game_rooms/_form.html.erb
<%= form_with(model: game_room, class: "contents") do |form| %>
  <% if game_room.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(game_room.errors.count, "error") %> prohibited this game_room from being saved:</h2>

      <ul>
        <% game_room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :game_data %>
    <%= form.text_field :game_data, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/game_rooms/_game_room.html.erb
<div id="<%= dom_id game_room %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= game_room.name %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Game data:</strong>
    <%= game_room.game_data %>
  </p>
  <p>
    <button type="button" data-action="hello#join_the_room" data-hello-room_id-param="<%= game_room.id %>" class="rounded-lg my-10 py-3 px-5 bg-blue-400 text-white">join the room</button>
    <button type="button" data-action="hello#startGame" data-hello-room_id-param="<%= game_room.id %>" class="rounded-lg my-10 py-3 px-5 bg-green-700 text-white">start Game</button>
    <button type="button" data-action="hello#playCardRandomly" data-hello-room_id-param="<%= game_room.id %>" class="rounded-lg my-10 py-3 px-5 bg-red-500 text-white">Play Card Randomly</button>
  </p>
  <% if action_name != "show" %>
    <%= link_to "Show this game room", game_room, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this game room', edit_game_room_path(game_room), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/game_rooms/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing game room</h1>

  <%= render "form", game_room: @game_room %>

  <%= link_to "Show this game room", @game_room, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to game rooms", game_rooms_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/game_rooms/index.html.erb
<%= turbo_stream_from "game_rooms" %>
<div class="w-full">
  <div>
    <% if current_user %>
      <%= link_to 'Log out', logout_path, data: { "turbo-method": :delete },
      class: "my-2 p-4 border-2 rounded-2xl inline-block border-slate-400 duration-300 hover:-translate-y-1" %>
    <% else %>
      <%= link_to 'Login with GitHub', auth_at_provider_path(:provider => :github),
      class: "my-2 p-4 border-2 rounded-2xl inline-block border-slate-400 duration-300 hover:-translate-y-1" %>
    <% end %>
    <% if current_user %>
      <p>
        is_external?: <%= current_user.external? %>
      </p>
      <p>
        name: <%= current_user.name %>
      </p>
      <p>
        email: <%= current_user.email %>
      </p>
      <p>
        user_id: <%= cookies.encrypted['user_id'] %>
      </p>
    <% end %>
  </div>
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Game rooms</h1>
    <%= link_to 'New game room', new_game_room_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>
  <div data-controller="hello">
    <div id="game_rooms" class="min-w-full">
      <%= render @game_rooms %>
    </div>
    <p class="font-bold text-2xl" data-hello-target="title"></p>
    <button type="button" data-action="hello#ping_the_room" class="rounded-lg py-3 px-5 bg-emerald-600 text-white">ping to the room</button>
  </div>
</div>

app/views/game_rooms/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New game room</h1>

  <%= render "form", game_room: @game_room %>

  <%= link_to 'Back to game rooms', game_rooms_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/game_rooms/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @game_room %>

    <%= link_to 'Edit this game_room', edit_game_room_path(@game_room), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this game_room', game_room_path(@game_room), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to game_rooms', game_rooms_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ironman2023Hanabi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
    <footer class="fixed flex justify-between bottom-0 left-0 w-full p-4 bg-white border-t border-gray-200 shadow">
      <a href="https://github.com/noracami/ironman2023-hanabi/" target="_blank" class="mr-4 hover:underline">Repo ==> https://github.com/noracami/ironman2023-hanabi/</a>
    </footer>
  </body>
</html>